name: security-ci
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --no-interaction --prefer-dist --no-progress
      - run: vendor/bin/phpstan analyse --error-format=github || true
      - run: npm ci
      - run: npm audit --audit-level=high || true
      - run: npm run build --if-present

  zap:
    uses: zaproxy/action-baseline@v0.11.0
    with:
      target: ${{ secrets.STAGING_URL }}
      fail_action: true
